# Generated by Django 4.2.6 on 2023-11-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0002_delete_rols'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Jefe de Departamento', 'Jefe de Departamento'), ('Maestro', 'Maestro'), ('Presidente de Academia (Ingenieria de Software)', 'Presidente de Academia (Ingenieria de Software)'), ('Presidente de Academia (Programacion Avanzada)', 'Presidente de Academia (Programacion Avanzada)'), ('Presidente de Academia(Gestion de Datos)', 'Presidente de Academia(Gestion de Datos)'), ('Presidente de Academia(Gestion de Tecnologias)', 'Presidente de Academia(Gestion de Tecnologias)')], default='Jefe de Departamento', max_length=100),
        ),
    ]
