# Generated by Django 4.2.6 on 2023-11-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0006_alter_customuser_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Operador', 'Operador'), ('Técnico', 'Técnico')], max_length=100),
        ),
    ]
