# Generated by Django 4.2.1 on 2023-10-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_reporte_jefe_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(upload_to='static\\files'),
        ),
    ]
