# Generated by Django 4.2.1 on 2023-10-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_alter_reporte_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='archivo',
        ),
    ]
