# Generated by Django 4.2.1 on 2023-10-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0005_remove_reporte_docentes_reporte_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='static/files'),
        ),
    ]
