# Generated by Django 4.2.6 on 2023-10-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0007_remove_reporte_jefe_departamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
