# Generated by Django 4.2.6 on 2023-11-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0012_reporte_jefe_departamento_alter_reporte_docentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='jefe_departamento',
        ),
    ]
