# Generated by Django 4.2.1 on 2023-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0013_remove_reporte_jefe_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
